# -*- coding: utf-8 -*-
"""DP_Coin Change

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4C4aaqPKB2UjMlUMjeVl4Ts8EiDSFgu
"""

import numpy as np

def coin_change(refer, coin_w):
  table = np.ones(coin_w) * np.inf
  table[0] = 0
  table[1] = 1
  table[2] = 2
  table[3] = 3
  table[4] = 4
  
  for x in range(coin_w):
    for y in range(len(refer)):
      if refer[y][1] <= x:
        a = table[x%refer[y][1]] + x//refer[y][1]
        if a <= table[x]:
          table[x] = a
  
  return table
        
reference_table = np.array([[1, 16], [2, 10], [3, 5], [4, 1]])
coin_weight = 21
z = coin_change(reference_table, coin_weight)
print(z)

table = np.ones(21) * np.inf
table[-4] = 0

print(5//3)
print(table)