# -*- coding: utf-8 -*-
"""Sort_Merge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10oKChGhpoim7HDY9naVw2gm754hB8EF5
"""

def divide(peter):
  a = int(len(peter)/2)
  listx = peter[0:a]
  listy = peter[a:]

  return listx, listy

def divide_x(a):
  c = list(range(1, 2*len(a)))
  c.insert(1, a)
  
  for z in range(1, len(a)):
    c[2*z], c[2*z+1] = divide(c[z])

  return c[len(a):2*len(a)]

b = [21, 10, 12, 20, 25, 13, 15, 22]
d = divide_x(b)
print(d)

d = list((21, 10, 12, 20, 25, 13, 15, 22))
    
def merge(a, b):
  len_a = len(a)
  len_b = len(b)
  k = a + b

  for x in range(len(a), 2*len(a)):
    for y in range(x-1, -1, -1):
      if k[y+1] < k[y]:
        c = k[y+1]
        k[y+1] = k[y]
        k[y] = c

  return k

def merge_x(x):
  z = list(range(0, len(x)))
  z.append(x)
  #print(z)

  for k in range(2*len(x), 0, -1):
    z[k] = merge(z[2*k], z[2*k+1])

  return z[1]

s = merge_x(d)