# -*- coding: utf-8 -*-
"""Sort_Bubble

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pzKsrzTxfMMqz5UCUnB2fD7TDZdHCnxe
"""

def bubble(a):
  for x in range(len(a)-1):
    for y in range(len(a)-x-1):
      if a[y] > a[y+1]:
        b = a[y]
        a[y] = a[y+1]
        a[y+1] = b

      y = 0
      
  return a

c = list((3, 6, 4, 9, 2, 99, 1, 104, 5, 8, 11, 1))
d = bubble(c)
print(d)