# -*- coding: utf-8 -*-
"""Sort_Quick

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QU8x8iMmljRZaZN0RzyoNWZgi8M2pQyp
"""

def quick(a):
  pivot = a.pop(int(len(a)/2))
  b = list(())
  c = list(())

  for x in range(len(a)):
    if a[x] < pivot:
      b.append(a[x])
    else:
      c.append(a[x])

  b.append(pivot)
  a = b + c
  b.remove(pivot)
  
  return b, c, a

c = list((1, 10, 11, 7, 9, 6, 2, 3, 99, 5, 1000))
d, e, f = quick(c)
print(e)
g, h, i = quick(e)
print(g, h, i)